### ISSUE TITLE
Trace panel not closed when trace is removed from server

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/vscode-trace-extension#104]
If a trace is removed from the `'OPENED TRACES` view using the remove button, then corresponding trace panel is not closed.

![vscode-remove-bug](https://user-images.githubusercontent.com/413424/225721930-a56e979d-461c-443b-b37c-0ccc193859f6.gif)

**Comment by ngondalia** [comment]
Picking this up
