### ISSUE TITLE
Trace Viewer icon dissapears when clicking another Side Bar button

### ISSUE THREAD

**Issue by hriday-panchasara** [eclipse-cdt-cloud/vscode-trace-extension#113]
[Screen Recording 2023-03-16 at 3.42.02 PM.webm](https://user-images.githubusercontent.com/92893187/225750728-01cc089a-63db-4d03-ba7a-3865b0627184.webm)

**Comment by hriday-panchasara** [comment]
Picked by Traviz

**Comment by bhufmann** [comment]
@hriday-panchasara are you able to reproduce this issue? On my end, I don't see this issue anymore. Please let me know.
