### ISSUE TITLE
Provide API to allow the capability to extend the trace extension

### ISSUE THREAD

**Issue by ngondalia** [eclipse-cdt-cloud/vscode-trace-extension#140]
Currently, there is no way for another extension to customize the Trace Viewer and add features onto the existing views. Adding this capability would be very beneficial for cases where someone wants to add another view to the trace viewer that is specific to their use case and would not be acceptable to add it to the base extension. For example, some trace types may want to show raw bytes of an event; They can contribute a Raw Bytes view to the trace viewer from their extension, and using the API provided by vscode-trace-extension, it can communicate the selected experiment, selected event, etc. The calling extension can then update their view accordingly.

Adding an API for an extension is quite simple with the VSCode API:
https://code.visualstudio.com/api/references/vscode-api#extensions

The alternative is to use VSCode commands, but it may not be scalable as the API grows larger.

For the initial API, I am interested in obtaining the experiment UUID of the current panel open in Trace Viewer. This issue can track the discussion of this feature, and the work for providing an API.

**Comment by bhufmann** [comment]
I think it would be good to have some APIs to allow to other extension to add custom functionality on top of the base trace extension. If every customization had to be implemented to the base trace extension then the TSP would have to be often modified to allow custom behaviours driven by the server back-ends. 

I'm wondering if the experiment UUID is all that is needed. Maybe the whole Experiment object would be useful when retrieving the current active panel. 

Also, would it be useful to provide a callback mechanism, when an experiment  is selected? The experiment selected change is already propagated inside the base trace extension.

I think the extension API should also provide the sever connection settings (URL, port etc),  a way to get notification about server status, update server status etc. I'm also wondering if the base extension should allow adding custom menu items at different locations in the base trace extensions as well as providing custom query parameters for a domain specific data provider. 

The latter suggestions for the extension APIs I see as future additions and not in scope of the initial extension API for the currently open panel. The initial API, however, should be a data structure where we can add additional APIs later on.
