### ISSUE TITLE
Endless switching of trace viewer tabs and selected traces after trace server start

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/vscode-trace-extension#238]
Having multiple traces open, then stop and start trace server, plus selecting tabs and traces after the trace server is finished starting, the view gets into the state that the tabs seems to be selected continuously. This can only be stopped by closing all traces but one. After that the available views are still updated for a while. 

It's looks like that there are signals sent internally in the trace viewer and they never stop being sent.

![vscode-samba-dancing](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/assets/413424/e7d721f5-5d8e-41f6-814c-d56d05325142)

**Comment by marcdumais-work** [comment]
I think maybe I have stumbled on an even simpler way to reproduce this issue. I will confirm and if so, capture a video.
