### ISSUE TITLE
How do I view statistical views?

### ISSUE THREAD

**Issue by dingzhouL** [eclipse-cdt-cloud/vscode-trace-extension#283]
version: v0.2.6

How do I view statistics through plug-ins? In trace-compass it supports the following:
![图片](https://github.com/user-attachments/assets/d3ae7b8e-b0f1-4905-ab93-bcd9b47c22f6)

**Comment by bhufmann** [comment]
Thanks for the interest in the vscode-trace-extension.

The event statistics view has not been migrated to the trace server. It means that there hasn't been a so-called data provider implemented in the Trace Compass trace server that can populate such view in the vscode-trace-extension.

**Comment by dingzhouL** [comment]
Thanks!
