### ISSUE TITLE
Display the status of the trace server

### ISSUE THREAD

**Issue by tahini** [eclipse-cdt-cloud/vscode-trace-extension#3]
When the `theia-trace-extension` shows the status of the of the server connection. When sending a back-end command, and if fails due to connection issues the status is updated to a red x. If it is successful the status is shown green. This should be provide here as well.

An additional web-view needs to be implemented for that. Note that the traceviewer-react-components needs to provide the view implementation so that the web-view only need so use it and provide UI controls.

![image](https://user-images.githubusercontent.com/413424/195105556-c547d3ac-cbb2-4a45-bb5f-b7fc3220f716.png)

**Comment by hriday-panchasara** [comment]
Fixed by https://github.com/eclipse-cdt-cloud/vscode-trace-extension/pull/120
