### ISSUE TITLE
Migrate view toolbar menus

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/vscode-trace-extension#38]
The theia-trace-extension provides different toolbar buttons for the widget view (where the graphs are loaded). This is Theia specific and doesn't exist in the VsCode version.

To support the same functionality this needs to be added to the vscode-trace-extension. 

First, it' needs to be investigated if it's the VsCode APIs allows it to add toolbar buttons. If yes, the functionality can be implemented using VsCode APIs. If not then the functionality needs to be added in a different way (maybe as part of the react-components). 

Note: Move as much code to the `theia-trace-extension` repository in the Theia independent packages (`traceviewer-react-components` and `traceviewer-base-components`) for code-re-use purposes.

**Trace Viewer widgets**
![image](https://user-images.githubusercontent.com/413424/153911027-9f41b21f-c9ac-46f6-b66a-e593b0483ebd.png)

**Comment by colin-grant-work** [comment]
The relevant contribution point to get toolbar items on the toolbar for a webview is the `.menus.view/title` contribution point with a `"when": "view == <view ID>"` clause.

**Comment by bhufmann** [comment]
> The relevant contribution point to get toolbar items on the toolbar for a webview is the `.menus.view/title` contribution point with a `"when": "view == <view ID>"` clause.

The middle "webview" panel where the graphs are, is opened programatically and not using the contribution point. We'll have to see if we can add the menu the same way.

**Comment by bhufmann** [comment]
With recent [VsCode version v1.71](https://code.visualstudio.com/updates/v1_71#_new-activewebviewpanelid-context-key) (August 2022) it is possible to add conditional editor menus with `activeWebviewPanelId`. However, this is not supported when installing the `vscode-trace-extension` in Theia. 

```json
      "editor/title": [
        {
          "when": "activeWebviewPanelId == 'react'",
          "command": "<command>",
          "group": "navigation"
        }
      ]
```

**Comment by bhufmann** [comment]
#96 adds the `reset time range` button and the `open overview` button. The others still have to be added. Here is the list:
- Undo/Redo button
- Help button for short cuts
- Marker menus
