### ISSUE TITLE
Update how component styles are defined

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/vscode-trace-extension#67]
Right now the styles are provided by css files stored here [1].  Not all values are defined in here and need to be added.

Theia theme variables are used because the `traceviewer-react-components` are using these variable name. This approach work, however, we should not use Theia names here. The variables in the components should have Theia or VsCode independent names and depending on if the components run in Theia or VsCode the mapping is defined there.

[1] https://github.com/theia-ide/vscode-trace-extension/tree/master/vscode-trace-webviews/src/style.

**Comment by hoangphamEclipse** [comment]
Picking up this issue.
